# train parameters
dataset: 'amazon'
seed: 20
epoch: 1000
early_stop: 200
lr: 0.1
weight_decay: 0.00005
cuda: 2
log: True
data_path: '../data/'
result_path: '../result/'


# model parameters
gamma1: 0.4
gamma2: 1.4
intra_dim: 8
n_class: 2
head: 4
n_layer: 2
dropout: 0.1

